const pronounsArray = ['ich', 'du', 'er', 'sie', 'es', 'wir', 'ihr', 'Sie'];
const verbsArray = ['sagen', 'fragen', 'lieben', 'lachen', 'wohnen', 'singen', 'tanzen', 'spielen', 'machen', 'arbeiten', 'antworten', 'hören'];
const machenArray = ['mache', 'machst', 'macht', 'machen'];
const sagenArray = ['sage', 'sagst', 'sagt', 'sagen'];
const fragenArray = ['frage', 'fragst', 'fragt', 'fragen'];
const liebenArray = ['liebe', 'liebst', 'liebt', 'lieben'];
const lachenArray = ['lache', 'lachst', 'lacht', 'lachen'];
const wohnenArray = ['wohne', 'wohnst', 'wohnt', 'wohnen'];
const singenArray = ['singe', 'singst', 'singt', 'singen'];
const tanzenArray = ['tanze', 'tanzst', 'tanzt', 'tanzen'];
const spielenArray = ['spiele', 'spielst', 'spielt', 'spielen'];
const arbeitenArray = ['arbeite', 'arbeitest', 'arbeitet', 'arbeiten'];
const antwortenArray = ['antworte', 'antwortest', 'antwortet', 'antworten'];
const horenArray = ['höre', 'hörst', 'hört', 'hören'];
const seinArray = ['bin', 'bist', 'ist', 'sind', 'seid'];
const habenArray = ['habe', 'hast', 'hat', 'haben', 'habt'];
const greetingWords = ['Guten', 'Morgen', 'Tag', 'Abend', 'Gute', 'Nacht', 'Auf', 'Wiedersein', 'Danke', 'schön', 'Bitte', 'Hallo', 'Tschüs', 'Wie', 'bitte'];
const questionWords = ['Was', 'Wer', 'Wo', 'Wann', 'Warum', 'Wie', 'Wen'];

export const data = {
    "pronouns": [
        { id: 1, task: 'я', answer: 'ich', pronouns: pronounsArray },
        { id: 2, task: 'ты', answer: 'du', pronouns: pronounsArray },
        { id: 3, task: 'он', answer: 'er', pronouns: pronounsArray },
        { id: 4, task: 'она / они', answer: 'sie', pronouns: pronounsArray },
        { id: 5, task: 'оно', answer: 'es', pronouns: pronounsArray },
        { id: 6, task: 'мы', answer: 'wir', pronouns: pronounsArray },
        { id: 7, task: 'вы', answer: 'ihr', pronouns: pronounsArray },
        { id: 8, task: 'Вы', answer: 'Sie', pronouns: pronounsArray },
    ],
    "verbs": [
        { id: 1, task: 'говорить', answer: 'sagen', variants: verbsArray },
        { id: 2, task: 'спрашивать', answer: 'fragen', variants: verbsArray },
        { id: 3, task: 'любить', answer: 'lieben', variants: verbsArray },
        { id: 4, task: 'смеяться', answer: 'lachen', variants: verbsArray },
        { id: 5, task: 'жить, проживать', answer: 'wohnen', variants: verbsArray },
        { id: 6, task: 'петь', answer: 'singen', variants: verbsArray },
        { id: 7, task: 'танцевать', answer: 'tanzen', variants: verbsArray },
        { id: 8, task: 'играть', answer: 'spielen', variants: verbsArray },
        { id: 9, task: 'делать', answer: 'machen', variants: verbsArray },
        { id: 10, task: 'работать', answer: 'arbeiten', variants: verbsArray },
        { id: 11, task: 'отвечать', answer: 'antworten', variants: verbsArray },
        { id: 12, task: 'слышать', answer: 'hören', variants: verbsArray },
    ],
    "statements": [
        { id: 1, task: 'я делаю', answer: 'ich mache', variants: machenArray, pronouns: pronounsArray },
        { id: 2, task: 'ты делаешь', answer: 'du machst', variants: machenArray, pronouns: pronounsArray },
        { id: 3, task: 'он делает', answer: 'er macht', variants: machenArray, pronouns: pronounsArray },
        { id: 4, task: 'она делает', answer: 'sie macht', variants: machenArray, pronouns: pronounsArray },
        { id: 5, task: 'оно делает', answer: 'es macht', variants: machenArray, pronouns: pronounsArray },
        { id: 6, task: 'мы делаем', answer: 'wir machen', variants: machenArray, pronouns: pronounsArray },
        { id: 7, task: 'вы делаете', answer: 'ihr macht', variants: machenArray, pronouns: pronounsArray },
        { id: 8, task: 'они делают', answer: 'sie machen', variants: machenArray, pronouns: pronounsArray },
        { id: 9, task: 'Вы делаете', answer: 'Sie machen', variants: machenArray, pronouns: pronounsArray },

        { id: 10, task: 'я говорю', answer: 'ich sage', variants: sagenArray, pronouns: pronounsArray },
        { id: 11, task: 'ты говоришь', answer: 'du sagst', variants: sagenArray, pronouns: pronounsArray },
        { id: 12, task: 'он говорит', answer: 'er sagt', variants: sagenArray, pronouns: pronounsArray },
        { id: 13, task: 'она говорит', answer: 'sie sagt', variants: sagenArray, pronouns: pronounsArray },
        { id: 14, task: 'оно говорит', answer: 'es sagt', variants: sagenArray, pronouns: pronounsArray },
        { id: 15, task: 'мы говорим', answer: 'wir sagen', variants: sagenArray, pronouns: pronounsArray },
        { id: 16, task: 'вы говорите', answer: 'ihr sagt', variants: sagenArray, pronouns: pronounsArray },
        { id: 17, task: 'они говорят', answer: 'sie sagen', variants: sagenArray, pronouns: pronounsArray },
        { id: 18, task: 'Вы говорите', answer: 'Sie sagen', variants: sagenArray, pronouns: pronounsArray },

        { id: 11, task: 'я спрашиваю', answer: 'ich frage', variants: fragenArray, pronouns: pronounsArray },
        { id: 12, task: 'ты спрашиваешь', answer: 'du fragst', variants: fragenArray, pronouns: pronounsArray },
        { id: 13, task: 'он спрашивает', answer: 'er fragt', variants: fragenArray, pronouns: pronounsArray },
        { id: 14, task: 'она спрашивает', answer: 'sie fragt', variants: fragenArray, pronouns: pronounsArray },
        { id: 15, task: 'оно спрашивает', answer: 'es fragt', variants: fragenArray, pronouns: pronounsArray },
        { id: 16, task: 'мы спрашиваем', answer: 'wir fragen', variants: fragenArray, pronouns: pronounsArray },
        { id: 17, task: 'вы спрашиваете', answer: 'ihr fragt', variants: fragenArray, pronouns: pronounsArray },
        { id: 18, task: 'они спршивают', answer: 'sie fragen', variants: fragenArray, pronouns: pronounsArray },
        { id: 19, task: 'Вы спрашиваете', answer: 'Sie fragen', variants: fragenArray, pronouns: pronounsArray },

        { id: 20, task: 'я люблю', answer: 'ich liebe', variants: liebenArray, pronouns: pronounsArray },
        { id: 21, task: 'ты любишь', answer: 'du liebst', variants: liebenArray, pronouns: pronounsArray },
        { id: 22, task: 'он любит', answer: 'er liebt', variants: liebenArray, pronouns: pronounsArray },
        { id: 23, task: 'она любит', answer: 'sie liebt', variants: liebenArray, pronouns: pronounsArray },
        { id: 24, task: 'оно любит', answer: 'es liebt', variants: liebenArray, pronouns: pronounsArray },
        { id: 25, task: 'мы любит', answer: 'wir lieben', variants: liebenArray, pronouns: pronounsArray },
        { id: 26, task: 'вы любите', answer: 'ihr liebt', variants: liebenArray, pronouns: pronounsArray },
        { id: 27, task: 'они любят', answer: 'sie lieben', variants: liebenArray, pronouns: pronounsArray },
        { id: 28, task: 'Вы любите', answer: 'Sie lieben', variants: liebenArray, pronouns: pronounsArray },

        { id: 29, task: 'я смеюсь', answer: 'ich lache', variants: lachenArray, pronouns: pronounsArray },
        { id: 30, task: 'ты смеёшься', answer: 'du lachst', variants: lachenArray, pronouns: pronounsArray },
        { id: 31, task: 'он смеётся', answer: 'er lacht', variants: lachenArray, pronouns: pronounsArray },
        { id: 32, task: 'она смеётся', answer: 'sie lacht', variants: lachenArray, pronouns: pronounsArray },
        { id: 33, task: 'оно смеётся', answer: 'es lacht', variants: lachenArray, pronouns: pronounsArray },
        { id: 34, task: 'мы смеёмся', answer: 'wir lachen', variants: lachenArray, pronouns: pronounsArray },
        { id: 35, task: 'вы смеётесь', answer: 'ihr lacht', variants: lachenArray, pronouns: pronounsArray },
        { id: 36, task: 'они смеются', answer: 'sie lachen', variants: lachenArray, pronouns: pronounsArray },
        { id: 37, task: 'Вы смеётесь', answer: 'Sie lachen', variants: lachenArray, pronouns: pronounsArray },

        { id: 38, task: 'я живу', answer: 'ich wohne', variants: wohnenArray, pronouns: pronounsArray },
        { id: 39, task: 'ты живёшь', answer: 'du wohnst', variants: wohnenArray, pronouns: pronounsArray },
        { id: 40, task: 'он живёт', answer: 'er wohnt', variants: wohnenArray, pronouns: pronounsArray },
        { id: 41, task: 'она живёт', answer: 'sie wohnt', variants: wohnenArray, pronouns: pronounsArray },
        { id: 42, task: 'оно живёт', answer: 'es wohnt', variants: wohnenArray, pronouns: pronounsArray },
        { id: 43, task: 'мы живём', answer: 'wir wohnen', variants: wohnenArray, pronouns: pronounsArray },
        { id: 44, task: 'вы живёте', answer: 'ihr wohnt', variants: wohnenArray, pronouns: pronounsArray },
        { id: 45, task: 'они живут', answer: 'sie wohnen', variants: wohnenArray, pronouns: pronounsArray },
        { id: 46, task: 'Вы живёте', answer: 'Sie wohnen', variants: wohnenArray, pronouns: pronounsArray },

        { id: 47, task: 'я пою', answer: 'ich singe', variants: singenArray, pronouns: pronounsArray },
        { id: 48, task: 'ты поёшь', answer: 'du singst', variants: singenArray, pronouns: pronounsArray },
        { id: 49, task: 'он поёт', answer: 'er singt', variants: singenArray, pronouns: pronounsArray },
        { id: 50, task: 'она поёт', answer: 'sie singt', variants: singenArray, pronouns: pronounsArray },
        { id: 51, task: 'оно поёт', answer: 'es singt', variants: singenArray, pronouns: pronounsArray },
        { id: 52, task: 'мы поём', answer: 'wir singen', variants: singenArray, pronouns: pronounsArray },
        { id: 53, task: 'вы поёте', answer: 'ihr singt', variants: singenArray, pronouns: pronounsArray },
        { id: 54, task: 'они поют', answer: 'sie singen', variants: singenArray, pronouns: pronounsArray },
        { id: 55, task: 'Вы поёте', answer: 'Sie singen', variants: singenArray, pronouns: pronounsArray },

        { id: 56, task: 'я танцую', answer: 'ich tanze', variants: tanzenArray, pronouns: pronounsArray },
        { id: 57, task: 'ты танцуешь', answer: 'du tanzst', variants: tanzenArray, pronouns: pronounsArray },
        { id: 58, task: 'он танцует', answer: 'er tanzt', variants: tanzenArray, pronouns: pronounsArray },
        { id: 59, task: 'она танцует', answer: 'sie tanzt', variants: tanzenArray, pronouns: pronounsArray },
        { id: 60, task: 'оно танцует', answer: 'es tanzt', variants: tanzenArray, pronouns: pronounsArray },
        { id: 61, task: 'мы танцуем', answer: 'wir tanzen', variants: tanzenArray, pronouns: pronounsArray },
        { id: 62, task: 'вы танцуете', answer: 'ihr tanzt', variants: tanzenArray, pronouns: pronounsArray },
        { id: 63, task: 'они танцуют', answer: 'sie tanzen', variants: tanzenArray, pronouns: pronounsArray },
        { id: 64, task: 'Вы танцуете', answer: 'Sie tanzen', variants: tanzenArray, pronouns: pronounsArray },

        { id: 65, task: 'я играю', answer: 'ich spiele', variants: spielenArray, pronouns: pronounsArray },
        { id: 66, task: 'ты играешь', answer: 'du spielst', variants: spielenArray, pronouns: pronounsArray },
        { id: 67, task: 'он играет', answer: 'er spielt', variants: spielenArray, pronouns: pronounsArray },
        { id: 68, task: 'она играет', answer: 'sie spielt', variants: spielenArray, pronouns: pronounsArray },
        { id: 69, task: 'оно играет', answer: 'es spielt', variants: spielenArray, pronouns: pronounsArray },
        { id: 70, task: 'мы играем', answer: 'wir spielen', variants: spielenArray, pronouns: pronounsArray },
        { id: 71, task: 'вы играете', answer: 'ihr spielt', variants: spielenArray, pronouns: pronounsArray },
        { id: 72, task: 'они играют', answer: 'sie spielen', variants: spielenArray, pronouns: pronounsArray },
        { id: 73, task: 'Вы играете', answer: 'Sie spielen', variants: spielenArray, pronouns: pronounsArray },

        { id: 74, task: 'я работаю', answer: 'ich arbeite', variants: arbeitenArray, pronouns: pronounsArray },
        { id: 75, task: 'ты работаешь', answer: 'du arbeitest', variants: arbeitenArray, pronouns: pronounsArray },
        { id: 76, task: 'он работает', answer: 'er arbeitet', variants: arbeitenArray, pronouns: pronounsArray },
        { id: 77, task: 'она работает', answer: 'sie arbeitet', variants: arbeitenArray, pronouns: pronounsArray },
        { id: 78, task: 'оно работает', answer: 'es arbeitet', variants: arbeitenArray, pronouns: pronounsArray },
        { id: 79, task: 'мы работаем', answer: 'wir arbeiten', variants: arbeitenArray, pronouns: pronounsArray },
        { id: 80, task: 'вы работаете', answer: 'ihr arbeitet', variants: arbeitenArray, pronouns: pronounsArray },
        { id: 81, task: 'они работают', answer: 'sie arbeiten', variants: arbeitenArray, pronouns: pronounsArray },
        { id: 82, task: 'Вы работаете', answer: 'Sie arbeiten', variants: arbeitenArray, pronouns: pronounsArray },

        { id: 83, task: 'я отвечаю', answer: 'ich antworte', variants: antwortenArray, pronouns: pronounsArray },
        { id: 84, task: 'ты отвечаешь', answer: 'du antwortest', variants: antwortenArray, pronouns: pronounsArray },
        { id: 85, task: 'он отвечает', answer: 'er antwortet', variants: antwortenArray, pronouns: pronounsArray },
        { id: 86, task: 'она отвечает', answer: 'sie antwortet', variants: antwortenArray, pronouns: pronounsArray },
        { id: 87, task: 'оно отвечает', answer: 'es antwortet', variants: antwortenArray, pronouns: pronounsArray },
        { id: 88, task: 'мы отвечаем', answer: 'wir antworten', variants: antwortenArray, pronouns: pronounsArray },
        { id: 89, task: 'вы отвечаете', answer: 'ihr antwortet', variants: antwortenArray, pronouns: pronounsArray },
        { id: 90, task: 'они отвечают', answer: 'sie antworten', variants: antwortenArray, pronouns: pronounsArray },
        { id: 91, task: 'Вы отвечаете', answer: 'Sie antworten', variants: antwortenArray, pronouns: pronounsArray },

        { id: 92, task: 'я слышу', answer: 'ich höre', variants: horenArray, pronouns: pronounsArray },
        { id: 93, task: 'ты слышишь', answer: 'du hörst', variants: horenArray, pronouns: pronounsArray },
        { id: 94, task: 'он слышит', answer: 'er hört', variants: horenArray, pronouns: pronounsArray },
        { id: 95, task: 'она слышит', answer: 'sie hört', variants: horenArray, pronouns: pronounsArray },
        { id: 96, task: 'оно слышит', answer: 'es hört', variants: horenArray, pronouns: pronounsArray },
        { id: 97, task: 'мы слышим', answer: 'wir hören', variants: horenArray, pronouns: pronounsArray },
        { id: 98, task: 'вы слышите', answer: 'ihr hört', variants: horenArray, pronouns: pronounsArray },
        { id: 99, task: 'они слышут', answer: 'sie hören', variants: horenArray, pronouns: pronounsArray },
        { id: 100, task: 'Вы слышите', answer: 'Sie hören', variants: horenArray, pronouns: pronounsArray },
    ],
    "negatives": [
        { id: 1, task: 'я не делаю', answer: 'ich mache nicht', variants: machenArray, pronouns: pronounsArray },
        { id: 2, task: 'ты не делаешь', answer: 'du machst nicht', variants: machenArray, pronouns: pronounsArray },
        { id: 3, task: 'он не делает', answer: 'er macht nicht', variants: machenArray, pronouns: pronounsArray },
        { id: 4, task: 'она не делает', answer: 'sie macht nicht', variants: machenArray, pronouns: pronounsArray },
        { id: 5, task: 'оно не делает', answer: 'es macht nicht', variants: machenArray, pronouns: pronounsArray },
        { id: 6, task: 'мы не делаем', answer: 'wir machen nicht', variants: machenArray, pronouns: pronounsArray },
        { id: 7, task: 'вы не делаете', answer: 'ihr macht nicht', variants: machenArray, pronouns: pronounsArray },
        { id: 8, task: 'они не делают', answer: 'sie machen nicht', variants: machenArray, pronouns: pronounsArray },
        { id: 9, task: 'Вы не делаете', answer: 'Sie machen nicht', variants: machenArray, pronouns: pronounsArray },

        { id: 10, task: 'я не говорю', answer: 'ich sage nicht', variants: sagenArray, pronouns: pronounsArray },
        { id: 11, task: 'ты не говоришь', answer: 'du sagst nicht', variants: sagenArray, pronouns: pronounsArray },
        { id: 12, task: 'он не говорит', answer: 'er sagt nicht', variants: sagenArray, pronouns: pronounsArray },
        { id: 13, task: 'она не говорит', answer: 'sie sagt nicht', variants: sagenArray, pronouns: pronounsArray },
        { id: 14, task: 'оно не говорит', answer: 'es sagt nicht', variants: sagenArray, pronouns: pronounsArray },
        { id: 15, task: 'мы не говорим', answer: 'wir sagen nicht', variants: sagenArray, pronouns: pronounsArray },
        { id: 16, task: 'вы не говорите', answer: 'ihr sagt nicht', variants: sagenArray, pronouns: pronounsArray },
        { id: 17, task: 'они не говорят', answer: 'sie sagen nicht', variants: sagenArray, pronouns: pronounsArray },
        { id: 18, task: 'Вы не говорите', answer: 'Sie sagen nicht', variants: sagenArray, pronouns: pronounsArray },

        { id: 11, task: 'я не спрашиваю', answer: 'ich frage nicht', variants: fragenArray, pronouns: pronounsArray },
        { id: 12, task: 'ты не спрашиваешь', answer: 'du fragst nicht', variants: fragenArray, pronouns: pronounsArray },
        { id: 13, task: 'он не спрашивает', answer: 'er fragt nicht', variants: fragenArray, pronouns: pronounsArray },
        { id: 14, task: 'она не спрашивает', answer: 'sie fragt nicht', variants: fragenArray, pronouns: pronounsArray },
        { id: 15, task: 'оно не спрашивает', answer: 'es fragt nicht', variants: fragenArray, pronouns: pronounsArray },
        { id: 16, task: 'мы не спрашиваем', answer: 'wir fragen nicht', variants: fragenArray, pronouns: pronounsArray },
        { id: 17, task: 'вы не спрашиваете', answer: 'ihr fragt nicht', variants: fragenArray, pronouns: pronounsArray },
        { id: 18, task: 'они не спршивают', answer: 'sie fragen nicht', variants: fragenArray, pronouns: pronounsArray },
        { id: 19, task: 'Вы не спрашиваете', answer: 'Sie fragen nicht', variants: fragenArray, pronouns: pronounsArray },

        { id: 20, task: 'я не люблю', answer: 'ich liebe nicht', variants: liebenArray, pronouns: pronounsArray },
        { id: 21, task: 'ты не любишь', answer: 'du liebst nicht', variants: liebenArray, pronouns: pronounsArray },
        { id: 22, task: 'он не любит', answer: 'er liebt nicht', variants: liebenArray, pronouns: pronounsArray },
        { id: 23, task: 'она не любит', answer: 'sie liebt nicht', variants: liebenArray, pronouns: pronounsArray },
        { id: 24, task: 'оно не любит', answer: 'es liebt nicht', variants: liebenArray, pronouns: pronounsArray },
        { id: 25, task: 'мы не любит', answer: 'wir lieben nicht', variants: liebenArray, pronouns: pronounsArray },
        { id: 26, task: 'вы не любите', answer: 'ihr liebt nicht', variants: liebenArray, pronouns: pronounsArray },
        { id: 27, task: 'они не любят', answer: 'sie lieben nicht', variants: liebenArray, pronouns: pronounsArray },
        { id: 28, task: 'Вы не любите', answer: 'Sie lieben nicht', variants: liebenArray, pronouns: pronounsArray },

        { id: 29, task: 'я не смеюсь', answer: 'ich lache nicht', variants: lachenArray, pronouns: pronounsArray },
        { id: 30, task: 'ты не смеёшься', answer: 'du lachst nicht', variants: lachenArray, pronouns: pronounsArray },
        { id: 31, task: 'он не смеётся', answer: 'er lacht nicht', variants: lachenArray, pronouns: pronounsArray },
        { id: 32, task: 'она не смеётся', answer: 'sie lacht nicht', variants: lachenArray, pronouns: pronounsArray },
        { id: 33, task: 'оно не смеётся', answer: 'es lacht nicht', variants: lachenArray, pronouns: pronounsArray },
        { id: 34, task: 'мы не смеёмся', answer: 'wir lachen nicht', variants: lachenArray, pronouns: pronounsArray },
        { id: 35, task: 'вы не смеётесь', answer: 'ihr lacht nicht', variants: lachenArray, pronouns: pronounsArray },
        { id: 36, task: 'они не смеются', answer: 'sie lachen nicht', variants: lachenArray, pronouns: pronounsArray },
        { id: 37, task: 'Вы не смеётесь', answer: 'Sie lachen nicht', variants: lachenArray, pronouns: pronounsArray },

        { id: 38, task: 'я не живу', answer: 'ich wohne nicht', variants: wohnenArray, pronouns: pronounsArray },
        { id: 39, task: 'ты не живёшь', answer: 'du wohnst nicht', variants: wohnenArray, pronouns: pronounsArray },
        { id: 40, task: 'он не живёт', answer: 'er wohnt nicht', variants: wohnenArray, pronouns: pronounsArray },
        { id: 41, task: 'она не живёт', answer: 'sie wohnt nicht', variants: wohnenArray, pronouns: pronounsArray },
        { id: 42, task: 'оно не живёт', answer: 'es wohnt nicht', variants: wohnenArray, pronouns: pronounsArray },
        { id: 43, task: 'мы не живём', answer: 'wir wohnen nicht', variants: wohnenArray, pronouns: pronounsArray },
        { id: 44, task: 'вы не живёте', answer: 'ihr wohnt nicht', variants: wohnenArray, pronouns: pronounsArray },
        { id: 45, task: 'они не живут', answer: 'sie wohnen nicht', variants: wohnenArray, pronouns: pronounsArray },
        { id: 46, task: 'Вы не живёте', answer: 'Sie wohnen nicht', variants: wohnenArray, pronouns: pronounsArray },

        { id: 47, task: 'я не пою', answer: 'ich singe nicht', variants: singenArray, pronouns: pronounsArray },
        { id: 48, task: 'ты не поёшь', answer: 'du singst nicht', variants: singenArray, pronouns: pronounsArray },
        { id: 49, task: 'он не поёт', answer: 'er singt nicht', variants: singenArray, pronouns: pronounsArray },
        { id: 50, task: 'она не поёт', answer: 'sie singt nicht', variants: singenArray, pronouns: pronounsArray },
        { id: 51, task: 'оно не поёт', answer: 'es singt nicht', variants: singenArray, pronouns: pronounsArray },
        { id: 52, task: 'мы не поём', answer: 'wir singen nicht', variants: singenArray, pronouns: pronounsArray },
        { id: 53, task: 'вы не поёте', answer: 'ihr singt nicht', variants: singenArray, pronouns: pronounsArray },
        { id: 54, task: 'они не поют', answer: 'sie singen nicht', variants: singenArray, pronouns: pronounsArray },
        { id: 55, task: 'Вы не поёте', answer: 'Sie singen nicht', variants: singenArray, pronouns: pronounsArray },

        { id: 56, task: 'я не танцую', answer: 'ich tanze nicht', variants: tanzenArray, pronouns: pronounsArray },
        { id: 57, task: 'ты не танцуешь', answer: 'du tanzst nicht', variants: tanzenArray, pronouns: pronounsArray },
        { id: 58, task: 'он не танцует', answer: 'er tanzt nicht', variants: tanzenArray, pronouns: pronounsArray },
        { id: 59, task: 'она не танцует', answer: 'sie tanzt nicht', variants: tanzenArray, pronouns: pronounsArray },
        { id: 60, task: 'оно не танцует', answer: 'es tanzt nicht', variants: tanzenArray, pronouns: pronounsArray },
        { id: 61, task: 'мы не танцуем', answer: 'wir tanzen nicht', variants: tanzenArray, pronouns: pronounsArray },
        { id: 62, task: 'вы не танцуете', answer: 'ihr tanzt nicht', variants: tanzenArray, pronouns: pronounsArray },
        { id: 63, task: 'они не танцуют', answer: 'sie tanzen nicht', variants: tanzenArray, pronouns: pronounsArray },
        { id: 64, task: 'Вы не танцуете', answer: 'Sie tanzen nicht', variants: tanzenArray, pronouns: pronounsArray },

        { id: 65, task: 'я не играю', answer: 'ich spiele nicht', variants: spielenArray, pronouns: pronounsArray },
        { id: 66, task: 'ты не играешь', answer: 'du spielst nicht', variants: spielenArray, pronouns: pronounsArray },
        { id: 67, task: 'он не играет', answer: 'er spielt nicht', variants: spielenArray, pronouns: pronounsArray },
        { id: 68, task: 'она не играет', answer: 'sie spielt nicht', variants: spielenArray, pronouns: pronounsArray },
        { id: 69, task: 'оно не играет', answer: 'es spielt nicht', variants: spielenArray, pronouns: pronounsArray },
        { id: 70, task: 'мы не играем', answer: 'wir spielen nicht', variants: spielenArray, pronouns: pronounsArray },
        { id: 71, task: 'вы не играете', answer: 'ihr spielt nicht', variants: spielenArray, pronouns: pronounsArray },
        { id: 72, task: 'они не играют', answer: 'sie spielen nicht', variants: spielenArray, pronouns: pronounsArray },
        { id: 73, task: 'Вы не играете', answer: 'Sie spielen nicht', variants: spielenArray, pronouns: pronounsArray },

        { id: 74, task: 'я не работаю', answer: 'ich arbeite nicht', variants: arbeitenArray, pronouns: pronounsArray },
        { id: 75, task: 'ты не работаешь', answer: 'du arbeitest nicht', variants: arbeitenArray, pronouns: pronounsArray },
        { id: 76, task: 'он не работает', answer: 'er arbeitet nicht', variants: arbeitenArray, pronouns: pronounsArray },
        { id: 77, task: 'она не работает', answer: 'sie arbeitet nicht', variants: arbeitenArray, pronouns: pronounsArray },
        { id: 78, task: 'оно не работает', answer: 'es arbeitet nicht', variants: arbeitenArray, pronouns: pronounsArray },
        { id: 79, task: 'мы не работаем', answer: 'wir arbeiten nicht', variants: arbeitenArray, pronouns: pronounsArray },
        { id: 80, task: 'вы не работаете', answer: 'ihr arbeitet nicht', variants: arbeitenArray, pronouns: pronounsArray },
        { id: 81, task: 'они не работают', answer: 'sie arbeiten nicht', variants: arbeitenArray, pronouns: pronounsArray },
        { id: 82, task: 'Вы не работаете', answer: 'Sie arbeiten nicht', variants: arbeitenArray, pronouns: pronounsArray },

        { id: 83, task: 'я не отвечаю', answer: 'ich antworte nicht', variants: antwortenArray, pronouns: pronounsArray },
        { id: 84, task: 'ты не отвечаешь', answer: 'du antwortest nicht', variants: antwortenArray, pronouns: pronounsArray },
        { id: 85, task: 'он не отвечает', answer: 'er antwortet nicht', variants: antwortenArray, pronouns: pronounsArray },
        { id: 86, task: 'она не отвечает', answer: 'sie antwortet nicht', variants: antwortenArray, pronouns: pronounsArray },
        { id: 87, task: 'оно не отвечает', answer: 'es antwortet nicht', variants: antwortenArray, pronouns: pronounsArray },
        { id: 88, task: 'мы не отвечаем', answer: 'wir antworten nicht', variants: antwortenArray, pronouns: pronounsArray },
        { id: 89, task: 'вы не отвечаете', answer: 'ihr antwortet nicht', variants: antwortenArray, pronouns: pronounsArray },
        { id: 90, task: 'они не отвечают', answer: 'sie antworten nicht', variants: antwortenArray, pronouns: pronounsArray },
        { id: 91, task: 'Вы не отвечаете', answer: 'Sie antworten nicht', variants: antwortenArray, pronouns: pronounsArray },

        { id: 92, task: 'я не слышу', answer: 'ich höre nicht', variants: horenArray, pronouns: pronounsArray },
        { id: 93, task: 'ты не слышишь', answer: 'du hörst nicht', variants: horenArray, pronouns: pronounsArray },
        { id: 94, task: 'он не слышит', answer: 'er hört nicht', variants: horenArray, pronouns: pronounsArray },
        { id: 95, task: 'она не слышит', answer: 'sie hört nicht', variants: horenArray, pronouns: pronounsArray },
        { id: 96, task: 'оно не слышит', answer: 'es hört nicht', variants: horenArray, pronouns: pronounsArray },
        { id: 97, task: 'мы не слышим', answer: 'wir hören nicht', variants: horenArray, pronouns: pronounsArray },
        { id: 98, task: 'вы не слышите', answer: 'ihr hört nicht', variants: horenArray, pronouns: pronounsArray },
        { id: 99, task: 'они не слышут', answer: 'sie hören nicht', variants: horenArray, pronouns: pronounsArray },
        { id: 100, task: 'Вы не слышите', answer: 'Sie hören nicht', variants: horenArray, pronouns: pronounsArray },
    ],
    "questions": [
        { id: 1, task: 'я делаю?', answer: 'mache ich?', variants: machenArray, pronouns: pronounsArray },
        { id: 2, task: 'ты делаешь?', answer: 'machst du?', variants: machenArray, pronouns: pronounsArray },
        { id: 3, task: 'он делает?', answer: 'macht er?', variants: machenArray, pronouns: pronounsArray },
        { id: 4, task: 'она делает?', answer: 'macht sie?', variants: machenArray, pronouns: pronounsArray },
        { id: 5, task: 'оно делает?', answer: 'macht es?', variants: machenArray, pronouns: pronounsArray },
        { id: 6, task: 'мы делаем?', answer: 'machen wir?', variants: machenArray, pronouns: pronounsArray },
        { id: 7, task: 'вы делаете?', answer: 'macht ihr?', variants: machenArray, pronouns: pronounsArray },
        { id: 8, task: 'они делают?', answer: 'machen sie?', variants: machenArray, pronouns: pronounsArray },
        { id: 9, task: 'Вы делаете?', answer: 'machen Sie?', variants: machenArray, pronouns: pronounsArray },

        { id: 10, task: 'я говорю?', answer: 'sage ich?', variants: sagenArray, pronouns: pronounsArray },
        { id: 11, task: 'ты говоришь?', answer: 'sagst du?', variants: sagenArray, pronouns: pronounsArray },
        { id: 12, task: 'он говорит?', answer: 'sagt er?', variants: sagenArray, pronouns: pronounsArray },
        { id: 13, task: 'она говорит?', answer: 'sagt sie?', variants: sagenArray, pronouns: pronounsArray },
        { id: 14, task: 'оно говорит?', answer: 'sagt es?', variants: sagenArray, pronouns: pronounsArray },
        { id: 15, task: 'мы говорим?', answer: 'sagen wir?', variants: sagenArray, pronouns: pronounsArray },
        { id: 16, task: 'вы говорите?', answer: 'sagt ihr?', variants: sagenArray, pronouns: pronounsArray },
        { id: 17, task: 'они говорят?', answer: 'sagen sie?', variants: sagenArray, pronouns: pronounsArray },
        { id: 18, task: 'Вы говорите?', answer: 'sagen Sie?', variants: sagenArray, pronouns: pronounsArray },

        { id: 11, task: 'я спрашиваю?', answer: 'frage ich?', variants: fragenArray, pronouns: pronounsArray },
        { id: 12, task: 'ты спрашиваешь?', answer: 'fragst du?', variants: fragenArray, pronouns: pronounsArray },
        { id: 13, task: 'он спрашивает?', answer: 'fragt er?', variants: fragenArray, pronouns: pronounsArray },
        { id: 14, task: 'она спрашивает?', answer: 'fragt sie?', variants: fragenArray, pronouns: pronounsArray },
        { id: 15, task: 'оно спрашивает?', answer: 'fragt es?', variants: fragenArray, pronouns: pronounsArray },
        { id: 16, task: 'мы спрашиваем?', answer: 'fragen wir?', variants: fragenArray, pronouns: pronounsArray },
        { id: 17, task: 'вы спрашиваете?', answer: 'fragt ihr?', variants: fragenArray, pronouns: pronounsArray },
        { id: 18, task: 'они спршивают?', answer: 'fragen sie?', variants: fragenArray, pronouns: pronounsArray },
        { id: 19, task: 'Вы спрашиваете?', answer: 'fragen Sie?', variants: fragenArray, pronouns: pronounsArray },

        { id: 20, task: 'я люблю?', answer: 'liebe ich?', variants: liebenArray, pronouns: pronounsArray },
        { id: 21, task: 'ты любишь?', answer: 'liebst du?', variants: liebenArray, pronouns: pronounsArray },
        { id: 22, task: 'он любит?', answer: 'liebt er?', variants: liebenArray, pronouns: pronounsArray },
        { id: 23, task: 'она любит?', answer: 'liebt sie?', variants: liebenArray, pronouns: pronounsArray },
        { id: 24, task: 'оно любит?', answer: 'liebt es?', variants: liebenArray, pronouns: pronounsArray },
        { id: 25, task: 'мы любит?', answer: 'lieben wir?', variants: liebenArray, pronouns: pronounsArray },
        { id: 26, task: 'вы любите?', answer: 'liebt ihr?', variants: liebenArray, pronouns: pronounsArray },
        { id: 27, task: 'они любят?', answer: 'lieben sie?', variants: liebenArray, pronouns: pronounsArray },
        { id: 28, task: 'Вы любите?', answer: 'lieben Sie?', variants: liebenArray, pronouns: pronounsArray },

        { id: 29, task: 'я смеюсь?', answer: 'lache ich?', variants: lachenArray, pronouns: pronounsArray },
        { id: 30, task: 'ты смеёшься?', answer: 'lachst du?', variants: lachenArray, pronouns: pronounsArray },
        { id: 31, task: 'он смеётся?', answer: 'lacht er?', variants: lachenArray, pronouns: pronounsArray },
        { id: 32, task: 'она смеётся?', answer: 'lacht sie?', variants: lachenArray, pronouns: pronounsArray },
        { id: 33, task: 'оно смеётся?', answer: 'lacht es?', variants: lachenArray, pronouns: pronounsArray },
        { id: 34, task: 'мы смеёмся?', answer: 'lachen wir?', variants: lachenArray, pronouns: pronounsArray },
        { id: 35, task: 'вы смеётесь?', answer: 'lacht ihr?', variants: lachenArray, pronouns: pronounsArray },
        { id: 36, task: 'они смеются?', answer: 'lachen sie?', variants: lachenArray, pronouns: pronounsArray },
        { id: 37, task: 'Вы смеётесь?', answer: 'lachen Sie?', variants: lachenArray, pronouns: pronounsArray },

        { id: 38, task: 'я живу?', answer: 'wohne ich?', variants: wohnenArray, pronouns: pronounsArray },
        { id: 39, task: 'ты живёшь?', answer: 'wohnst du?', variants: wohnenArray, pronouns: pronounsArray },
        { id: 40, task: 'он живёт?', answer: 'wohnt er?', variants: wohnenArray, pronouns: pronounsArray },
        { id: 41, task: 'она живёт?', answer: 'wohnt sie?', variants: wohnenArray, pronouns: pronounsArray },
        { id: 42, task: 'оно живёт?', answer: 'wohnt es?', variants: wohnenArray, pronouns: pronounsArray },
        { id: 43, task: 'мы живём?', answer: 'wohnen wir?', variants: wohnenArray, pronouns: pronounsArray },
        { id: 44, task: 'вы живёте?', answer: 'wohnt ihr?', variants: wohnenArray, pronouns: pronounsArray },
        { id: 45, task: 'они живут?', answer: 'wohnen sie?', variants: wohnenArray, pronouns: pronounsArray },
        { id: 46, task: 'Вы живёте?', answer: 'wohnen Sie?', variants: wohnenArray, pronouns: pronounsArray },

        { id: 47, task: 'я пою?', answer: 'singe ich?', variants: singenArray, pronouns: pronounsArray },
        { id: 48, task: 'ты поёшь?', answer: 'singst du?', variants: singenArray, pronouns: pronounsArray },
        { id: 49, task: 'он поёт?', answer: 'singt er?', variants: singenArray, pronouns: pronounsArray },
        { id: 50, task: 'она поёт?', answer: 'singt sie?', variants: singenArray, pronouns: pronounsArray },
        { id: 51, task: 'оно поёт?', answer: 'singt es?', variants: singenArray, pronouns: pronounsArray },
        { id: 52, task: 'мы поём?', answer: 'singen wir?', variants: singenArray, pronouns: pronounsArray },
        { id: 53, task: 'вы поёте?', answer: 'singt ihr?', variants: singenArray, pronouns: pronounsArray },
        { id: 54, task: 'они поют?', answer: 'singen sie?', variants: singenArray, pronouns: pronounsArray },
        { id: 55, task: 'Вы поёте?', answer: 'singen Sie?', variants: singenArray, pronouns: pronounsArray },

        { id: 56, task: 'я танцую?', answer: 'tanze ich?', variants: tanzenArray, pronouns: pronounsArray },
        { id: 57, task: 'ты танцуешь?', answer: 'tanzst du?', variants: tanzenArray, pronouns: pronounsArray },
        { id: 58, task: 'он танцует?', answer: 'tanzt er?', variants: tanzenArray, pronouns: pronounsArray },
        { id: 59, task: 'она танцует?', answer: 'tanzt sie?', variants: tanzenArray, pronouns: pronounsArray },
        { id: 60, task: 'оно танцует?', answer: 'tanzt es?', variants: tanzenArray, pronouns: pronounsArray },
        { id: 61, task: 'мы танцуем?', answer: 'tanzen wir?', variants: tanzenArray, pronouns: pronounsArray },
        { id: 62, task: 'вы танцуете?', answer: 'tanzt ihr?', variants: tanzenArray, pronouns: pronounsArray },
        { id: 63, task: 'они танцуют?', answer: 'tanzen sie?', variants: tanzenArray, pronouns: pronounsArray },
        { id: 64, task: 'Вы танцуете?', answer: 'tanzen Sie?', variants: tanzenArray, pronouns: pronounsArray },

        { id: 65, task: 'я играю?', answer: 'spiele ich?', variants: spielenArray, pronouns: pronounsArray },
        { id: 66, task: 'ты играешь?', answer: 'spielst du?', variants: spielenArray, pronouns: pronounsArray },
        { id: 67, task: 'он играет?', answer: 'spielt er?', variants: spielenArray, pronouns: pronounsArray },
        { id: 68, task: 'она играет?', answer: 'spielt sie?', variants: spielenArray, pronouns: pronounsArray },
        { id: 69, task: 'оно играет?', answer: 'spielt es?', variants: spielenArray, pronouns: pronounsArray },
        { id: 70, task: 'мы играем?', answer: 'spielen wir?', variants: spielenArray, pronouns: pronounsArray },
        { id: 71, task: 'вы играете?', answer: 'spielt ihr?', variants: spielenArray, pronouns: pronounsArray },
        { id: 72, task: 'они играют?', answer: 'spielen sie?', variants: spielenArray, pronouns: pronounsArray },
        { id: 73, task: 'Вы играете?', answer: 'spielen Sie?', variants: spielenArray, pronouns: pronounsArray },

        { id: 74, task: 'я работаю?', answer: 'arbeite ich?', variants: arbeitenArray, pronouns: pronounsArray },
        { id: 75, task: 'ты работаешь?', answer: 'arbeitest du?', variants: arbeitenArray, pronouns: pronounsArray },
        { id: 76, task: 'он работает?', answer: 'arbeitet er?', variants: arbeitenArray, pronouns: pronounsArray },
        { id: 77, task: 'она работает?', answer: 'arbeitet sie?', variants: arbeitenArray, pronouns: pronounsArray },
        { id: 78, task: 'оно работает?', answer: 'arbeitet es?', variants: arbeitenArray, pronouns: pronounsArray },
        { id: 79, task: 'мы работаем?', answer: 'arbeiten wir?', variants: arbeitenArray, pronouns: pronounsArray },
        { id: 80, task: 'вы работаете?', answer: 'arbeitet ihr?', variants: arbeitenArray, pronouns: pronounsArray },
        { id: 81, task: 'они работают?', answer: 'arbeiten sie?', variants: arbeitenArray, pronouns: pronounsArray },
        { id: 82, task: 'Вы работаете?', answer: 'arbeiten Sie?', variants: arbeitenArray, pronouns: pronounsArray },

        { id: 83, task: 'я отвечаю?', answer: 'antworte ich?', variants: antwortenArray, pronouns: pronounsArray },
        { id: 84, task: 'ты отвечаешь?', answer: 'antwortest du?', variants: antwortenArray, pronouns: pronounsArray },
        { id: 85, task: 'он отвечает?', answer: 'antwortet er?', variants: antwortenArray, pronouns: pronounsArray },
        { id: 86, task: 'она отвечает?', answer: 'antwortet sie?', variants: antwortenArray, pronouns: pronounsArray },
        { id: 87, task: 'оно отвечает?', answer: 'antwortet es?', variants: antwortenArray, pronouns: pronounsArray },
        { id: 88, task: 'мы отвечаем?', answer: 'antworten wir?', variants: antwortenArray, pronouns: pronounsArray },
        { id: 89, task: 'вы отвечаете?', answer: 'antwortet ihr?', variants: antwortenArray, pronouns: pronounsArray },
        { id: 90, task: 'они отвечают?', answer: 'antworten sie?', variants: antwortenArray, pronouns: pronounsArray },
        { id: 91, task: 'Вы отвечаете?', answer: 'antworten Sie?', variants: antwortenArray, pronouns: pronounsArray },

        { id: 92, task: 'я слышу?', answer: 'höre ich?', variants: horenArray, pronouns: pronounsArray },
        { id: 93, task: 'ты слышишь?', answer: 'hörst du?', variants: horenArray, pronouns: pronounsArray },
        { id: 94, task: 'он слышит?', answer: 'hört er?', variants: horenArray, pronouns: pronounsArray },
        { id: 95, task: 'она слышит?', answer: 'hört sie?', variants: horenArray, pronouns: pronounsArray },
        { id: 96, task: 'оно слышит?', answer: 'hört es?', variants: horenArray, pronouns: pronounsArray },
        { id: 97, task: 'мы слышим?', answer: 'hören wir?', variants: horenArray, pronouns: pronounsArray },
        { id: 98, task: 'вы слышите?', answer: 'hört ihr?', variants: horenArray, pronouns: pronounsArray },
        { id: 99, task: 'они слышут?', answer: 'hören sie?', variants: horenArray, pronouns: pronounsArray },
        { id: 100, task: 'Вы слышите?', answer: 'hören Sie?', variants: horenArray, pronouns: pronounsArray },
    ],
    "futures": [
        { id: 1, task: 'я не работаю завтра', answer: 'ich arbeite nicht morgen', variants: arbeitenArray, pronouns: pronounsArray },
        { id: 2, task: 'ты работаешь завтра', answer: 'du arbeitest morgen', variants: arbeitenArray, pronouns: pronounsArray },
        { id: 3, task: 'он работает завтра?', answer: 'arbeitet er morgen?', variants: arbeitenArray, pronouns: pronounsArray },
        { id: 4, task: 'она не работает завтра', answer: 'sie arbeitet nicht morgen', variants: arbeitenArray, pronouns: pronounsArray },
        { id: 5, task: 'оно работает завтра', answer: 'es arbeitet morgen', variants: arbeitenArray, pronouns: pronounsArray },
        { id: 6, task: 'мы работаем завтра', answer: 'wir arbeiten morgen', variants: arbeitenArray, pronouns: pronounsArray },
        { id: 7, task: 'вы не работаете завтра', answer: 'ihr arbeitet nicht morgen', variants: arbeitenArray, pronouns: pronounsArray },
        { id: 8, task: 'они работают завтра?', answer: 'arbeiten sie morgen?', variants: arbeitenArray, pronouns: pronounsArray },
        { id: 9, task: 'Вы не работаете завтра', answer: 'Sie arbeiten nicht morgen', variants: arbeitenArray, pronouns: pronounsArray },
    ],
    "irregularVerbSein": [
        { id: 1, task: 'я есть', answer: 'ich bin', variants: seinArray, pronouns: pronounsArray },
        { id: 2, task: 'ты есть', answer: 'du bist', variants: seinArray, pronouns: pronounsArray },
        { id: 3, task: 'он есть', answer: 'er ist', variants: seinArray, pronouns: pronounsArray },
        { id: 4, task: 'она есть', answer: 'sie ist', variants: seinArray, pronouns: pronounsArray },
        { id: 5, task: 'оно есть', answer: 'es ist', variants: seinArray, pronouns: pronounsArray },
        { id: 6, task: 'мы есть', answer: 'wir sind', variants: seinArray, pronouns: pronounsArray },
        { id: 7, task: 'вы есть', answer: 'ihr seid', variants: seinArray, pronouns: pronounsArray },
        { id: 8, task: 'они есть', answer: 'sie sind', variants: seinArray, pronouns: pronounsArray },
        { id: 9, task: 'Вы есть', answer: 'Sie sind', variants: seinArray, pronouns: pronounsArray },
    ],
    "irregularVerbHaben": [
        { id: 1, task: 'я имею', answer: 'ich habe', variants: habenArray, pronouns: pronounsArray },
        { id: 2, task: 'ты имеешь', answer: 'du hast', variants: habenArray, pronouns: pronounsArray },
        { id: 3, task: 'он имеет', answer: 'er hat', variants: habenArray, pronouns: pronounsArray },
        { id: 4, task: 'она имеет', answer: 'sie hat', variants: habenArray, pronouns: pronounsArray },
        { id: 5, task: 'оно имеет', answer: 'es hat', variants: habenArray, pronouns: pronounsArray },
        { id: 6, task: 'мы имеем', answer: 'wir haben', variants: habenArray, pronouns: pronounsArray },
        { id: 7, task: 'вы имеете', answer: 'ihr habt', variants: habenArray, pronouns: pronounsArray },
        { id: 8, task: 'они имеют', answer: 'sie haben', variants: habenArray, pronouns: pronounsArray },
        { id: 9, task: 'Вы имеете', answer: 'Sie haben', variants: habenArray, pronouns: pronounsArray },
    ],
    "greetingPhrases": [
        { id: 1, task: 'Доброе утро!', answer: 'Guten Morgen!', variants: greetingWords },
        { id: 2, task: 'Добрый день!', answer: 'Guten Tag!', variants: greetingWords },
        { id: 3, task: 'Добрый вечер!', answer: 'Guten Abend!', variants: greetingWords },
        { id: 4, task: 'Спокойной ночи!', answer: 'Gute Nacht!', variants: greetingWords },
        { id: 5, task: 'До свидания!', answer: 'Auf Wiedersein!', variants: greetingWords },
        { id: 6, task: 'Спасибо', answer: 'Danke', variants: greetingWords },
        { id: 7, task: 'Большое спасибо', answer: 'Danke schön', variants: greetingWords },
        { id: 8, task: 'Пожалуйста', answer: 'Bitte', variants: greetingWords },
        { id: 9, task: 'Привет!', answer: 'Hallo!', variants: greetingWords },
        { id: 10, task: 'Пока!', answer: 'Tschüs!', variants: greetingWords },
        { id: 11, task: 'Что-что?', answer: 'Wie, bitte?', variants: greetingWords },
    ],
    "pastStatements": [
        { id: 1, task: 'я сделал', answer: 'ich habe gemacht', variants: habenArray, pronouns: pronounsArray },
        { id: 2, task: 'ты сделал', answer: 'du hast gemacht', variants: habenArray, pronouns: pronounsArray },
        { id: 3, task: 'он сделал', answer: 'er hat gemacht', variants: habenArray, pronouns: pronounsArray },
        { id: 4, task: 'она сделала', answer: 'sie hat gemacht', variants: habenArray, pronouns: pronounsArray },
        { id: 5, task: 'оно сделало', answer: 'es hat gemacht', variants: habenArray, pronouns: pronounsArray },
        { id: 6, task: 'мы сделали', answer: 'wir haben gemacht', variants: habenArray, pronouns: pronounsArray },
        { id: 7, task: 'вы сделали', answer: 'ihr habt gemacht', variants: habenArray, pronouns: pronounsArray },
        { id: 8, task: 'они сделали', answer: 'sie haben gemacht', variants: habenArray, pronouns: pronounsArray },
        { id: 9, task: 'Вы сделали', answer: 'Sie haben gemacht', variants: habenArray, pronouns: pronounsArray },

        { id: 10, task: 'я танцевал', answer: 'ich habe getanzt', variants: habenArray, pronouns: pronounsArray },
        { id: 11, task: 'ты танцевал', answer: 'du hast getanzt', variants: habenArray, pronouns: pronounsArray },
        { id: 12, task: 'он танцевал', answer: 'er hat getanzt', variants: habenArray, pronouns: pronounsArray },
        { id: 13, task: 'она танцевала', answer: 'sie hat getanzt', variants: habenArray, pronouns: pronounsArray },
        { id: 14, task: 'оно танцевало', answer: 'es hat getanzt', variants: habenArray, pronouns: pronounsArray },
        { id: 15, task: 'мы танцевали', answer: 'wir haben getanzt', variants: habenArray, pronouns: pronounsArray },
        { id: 16, task: 'вы танцевали', answer: 'ihr habt getanzt', variants: habenArray, pronouns: pronounsArray },
        { id: 17, task: 'они танцевали', answer: 'sie haben getanzt', variants: habenArray, pronouns: pronounsArray },
        { id: 18, task: 'Вы танцевали', answer: 'Sie haben getanzt', variants: habenArray, pronouns: pronounsArray },

        { id: 19, task: 'я играл', answer: 'ich habe gespielt', variants: habenArray, pronouns: pronounsArray },
        { id: 20, task: 'ты играл', answer: 'du hast gespielt', variants: habenArray, pronouns: pronounsArray },
        { id: 21, task: 'он играл', answer: 'er hat gespielt', variants: habenArray, pronouns: pronounsArray },
        { id: 22, task: 'она играла', answer: 'sie hat gespielt', variants: habenArray, pronouns: pronounsArray },
        { id: 23, task: 'оно играло', answer: 'es hat gespielt', variants: habenArray, pronouns: pronounsArray },
        { id: 24, task: 'мы играли', answer: 'wir haben gespielt', variants: habenArray, pronouns: pronounsArray },
        { id: 25, task: 'вы играли', answer: 'ihr habt gespielt', variants: habenArray, pronouns: pronounsArray },
        { id: 26, task: 'они играли', answer: 'sie haben gespielt', variants: habenArray, pronouns: pronounsArray },
        { id: 27, task: 'Вы играли', answer: 'Sie haben gespielt', variants: habenArray, pronouns: pronounsArray },

        { id: 28, task: 'я сказал', answer: 'ich habe gesagt', variants: habenArray, pronouns: pronounsArray },
        { id: 29, task: 'ты сказал', answer: 'du hast gesagt', variants: habenArray, pronouns: pronounsArray },
        { id: 30, task: 'он сказал', answer: 'er hat gesagt', variants: habenArray, pronouns: pronounsArray },
        { id: 31, task: 'она сказала', answer: 'sie hat gesagt', variants: habenArray, pronouns: pronounsArray },
        { id: 32, task: 'оно сказало', answer: 'es hat gesagt', variants: habenArray, pronouns: pronounsArray },
        { id: 33, task: 'мы сказали', answer: 'wir haben gesagt', variants: habenArray, pronouns: pronounsArray },
        { id: 34, task: 'вы сказали', answer: 'ihr habt gesagt', variants: habenArray, pronouns: pronounsArray },
        { id: 35, task: 'они сказали', answer: 'sie haben gesagt', variants: habenArray, pronouns: pronounsArray },
        { id: 35, task: 'Вы сказали', answer: 'Sie haben gesagt', variants: habenArray, pronouns: pronounsArray },

        { id: 36, task: 'я спросил', answer: 'ich habe gefragt', variants: habenArray, pronouns: pronounsArray },
        { id: 37, task: 'ты спросил', answer: 'du hast gefragt', variants: habenArray, pronouns: pronounsArray },
        { id: 38, task: 'он спросил', answer: 'er hat gefragt', variants: habenArray, pronouns: pronounsArray },
        { id: 39, task: 'она спросила', answer: 'sie hat gefragt', variants: habenArray, pronouns: pronounsArray },
        { id: 40, task: 'оно спросило', answer: 'es hat gefragt', variants: habenArray, pronouns: pronounsArray },
        { id: 41, task: 'мы спросили', answer: 'wir haben gefragt', variants: habenArray, pronouns: pronounsArray },
        { id: 42, task: 'вы спросили', answer: 'ihr habt gefragt', variants: habenArray, pronouns: pronounsArray },
        { id: 43, task: 'они спросили', answer: 'sie haben gefragt', variants: habenArray, pronouns: pronounsArray },
        { id: 44, task: 'Вы спросили', answer: 'Sie haben gefragt', variants: habenArray, pronouns: pronounsArray },

        { id: 45, task: 'я любил', answer: 'ich habe geliebt', variants: habenArray, pronouns: pronounsArray },
        { id: 46, task: 'ты любил', answer: 'du hast geliebt', variants: habenArray, pronouns: pronounsArray },
        { id: 47, task: 'он любил', answer: 'er hat geliebt', variants: habenArray, pronouns: pronounsArray },
        { id: 48, task: 'она любила', answer: 'sie hat geliebt', variants: habenArray, pronouns: pronounsArray },
        { id: 49, task: 'оно любило', answer: 'es hat geliebt', variants: habenArray, pronouns: pronounsArray },
        { id: 50, task: 'мы любили', answer: 'wir haben geliebt', variants: habenArray, pronouns: pronounsArray },
        { id: 51, task: 'вы любили', answer: 'ihr habt geliebt', variants: habenArray, pronouns: pronounsArray },
        { id: 52, task: 'они любили', answer: 'sie haben geliebt', variants: habenArray, pronouns: pronounsArray },
        { id: 53, task: 'Вы любили', answer: 'Sie haben geliebt', variants: habenArray, pronouns: pronounsArray },

        { id: 53, task: 'я слышал', answer: 'ich habe gehört', variants: habenArray, pronouns: pronounsArray },
        { id: 54, task: 'ты слышал', answer: 'du hast gehört', variants: habenArray, pronouns: pronounsArray },
        { id: 55, task: 'он слышал', answer: 'er hat gehört', variants: habenArray, pronouns: pronounsArray },
        { id: 56, task: 'она слышала', answer: 'sie hat gehört', variants: habenArray, pronouns: pronounsArray },
        { id: 57, task: 'оно слышало', answer: 'es hat gehört', variants: habenArray, pronouns: pronounsArray },
        { id: 58, task: 'мы слышали', answer: 'wir haben gehört', variants: habenArray, pronouns: pronounsArray },
        { id: 59, task: 'вы слышали', answer: 'ihr habt gehört', variants: habenArray, pronouns: pronounsArray },
        { id: 60, task: 'они слышали', answer: 'sie haben gehört', variants: habenArray, pronouns: pronounsArray },
        { id: 61, task: 'Вы слышали', answer: 'Sie haben gehört', variants: habenArray, pronouns: pronounsArray },

        { id: 62, task: 'я ответил', answer: 'ich habe geantwortet', variants: habenArray, pronouns: pronounsArray },
        { id: 63, task: 'ты ответил', answer: 'du hast geantwortet', variants: habenArray, pronouns: pronounsArray },
        { id: 64, task: 'он ответил', answer: 'er hat geantwortet', variants: habenArray, pronouns: pronounsArray },
        { id: 65, task: 'она ответила', answer: 'sie hat geantwortet', variants: habenArray, pronouns: pronounsArray },
        { id: 66, task: 'оно ответило', answer: 'es hat geantwortet', variants: habenArray, pronouns: pronounsArray },
        { id: 67, task: 'мы ответили', answer: 'wir haben geantwortet', variants: habenArray, pronouns: pronounsArray },
        { id: 68, task: 'вы ответили', answer: 'ihr habt geantwortet', variants: habenArray, pronouns: pronounsArray },
        { id: 69, task: 'они ответили', answer: 'sie haben geantwortet', variants: habenArray, pronouns: pronounsArray },
        { id: 70, task: 'Вы ответили', answer: 'Sie haben geantwortet', variants: habenArray, pronouns: pronounsArray },
    ],
    "pastNegativeStatements": [
        { id: 1, task: 'я не сделал', answer: 'ich habe nicht gemacht', variants: habenArray, pronouns: pronounsArray },
        { id: 2, task: 'ты не сделал', answer: 'du hast nicht gemacht', variants: habenArray, pronouns: pronounsArray },
        { id: 3, task: 'он не сделал', answer: 'er hat nicht gemacht', variants: habenArray, pronouns: pronounsArray },
        { id: 4, task: 'она не сделала', answer: 'sie hat nicht gemacht', variants: habenArray, pronouns: pronounsArray },
        { id: 5, task: 'оно не сделало', answer: 'es hat nicht gemacht', variants: habenArray, pronouns: pronounsArray },
        { id: 6, task: 'мы не сделали', answer: 'wir haben nicht gemacht', variants: habenArray, pronouns: pronounsArray },
        { id: 7, task: 'вы не сделали', answer: 'ihr habt nicht gemacht', variants: habenArray, pronouns: pronounsArray },
        { id: 8, task: 'они не сделали', answer: 'sie haben nicht gemacht', variants: habenArray, pronouns: pronounsArray },
        { id: 9, task: 'Вы не сделали', answer: 'Sie haben nicht gemacht', variants: habenArray, pronouns: pronounsArray },

        { id: 10, task: 'я не танцевал', answer: 'ich habe nicht getanzt', variants: habenArray, pronouns: pronounsArray },
        { id: 11, task: 'ты не танцевал', answer: 'du hast nicht getanzt', variants: habenArray, pronouns: pronounsArray },
        { id: 12, task: 'он не танцевал', answer: 'er hat nicht getanzt', variants: habenArray, pronouns: pronounsArray },
        { id: 13, task: 'она не танцевала', answer: 'sie hat nicht getanzt', variants: habenArray, pronouns: pronounsArray },
        { id: 14, task: 'оно не танцевало', answer: 'es hat nicht getanzt', variants: habenArray, pronouns: pronounsArray },
        { id: 15, task: 'мы не танцевали', answer: 'wir haben nicht getanzt', variants: habenArray, pronouns: pronounsArray },
        { id: 16, task: 'вы не танцевали', answer: 'ihr habt nicht getanzt', variants: habenArray, pronouns: pronounsArray },
        { id: 17, task: 'они не танцевали', answer: 'sie haben nicht getanzt', variants: habenArray, pronouns: pronounsArray },
        { id: 18, task: 'Вы не танцевали', answer: 'Sie haben nicht getanzt', variants: habenArray, pronouns: pronounsArray },

        { id: 19, task: 'я не играл', answer: 'ich habe nicht gespielt', variants: habenArray, pronouns: pronounsArray },
        { id: 20, task: 'ты не играл', answer: 'du hast nicht gespielt', variants: habenArray, pronouns: pronounsArray },
        { id: 21, task: 'он не играл', answer: 'er hat nicht gespielt', variants: habenArray, pronouns: pronounsArray },
        { id: 22, task: 'она не играла', answer: 'sie hat nicht gespielt', variants: habenArray, pronouns: pronounsArray },
        { id: 23, task: 'оно не играло', answer: 'es hat nicht gespielt', variants: habenArray, pronouns: pronounsArray },
        { id: 24, task: 'мы не играли', answer: 'wir haben nicht gespielt', variants: habenArray, pronouns: pronounsArray },
        { id: 25, task: 'вы не играли', answer: 'ihr habt nicht gespielt', variants: habenArray, pronouns: pronounsArray },
        { id: 26, task: 'они не играли', answer: 'sie haben nicht gespielt', variants: habenArray, pronouns: pronounsArray },
        { id: 27, task: 'Вы не играли', answer: 'Sie haben nicht gespielt', variants: habenArray, pronouns: pronounsArray },

        { id: 28, task: 'я не сказал', answer: 'ich habe nicht gesagt', variants: habenArray, pronouns: pronounsArray },
        { id: 29, task: 'ты не сказал', answer: 'du hast nicht gesagt', variants: habenArray, pronouns: pronounsArray },
        { id: 30, task: 'он не сказал', answer: 'er hat nicht gesagt', variants: habenArray, pronouns: pronounsArray },
        { id: 31, task: 'она не сказала', answer: 'sie hat nicht gesagt', variants: habenArray, pronouns: pronounsArray },
        { id: 32, task: 'оно не сказало', answer: 'es hat nicht gesagt', variants: habenArray, pronouns: pronounsArray },
        { id: 33, task: 'мы не сказали', answer: 'wir haben nicht gesagt', variants: habenArray, pronouns: pronounsArray },
        { id: 34, task: 'вы не сказали', answer: 'ihr habt nicht gesagt', variants: habenArray, pronouns: pronounsArray },
        { id: 35, task: 'они не сказали', answer: 'sie haben nicht gesagt', variants: habenArray, pronouns: pronounsArray },
        { id: 35, task: 'Вы не сказали', answer: 'Sie haben nicht gesagt', variants: habenArray, pronouns: pronounsArray },

        { id: 36, task: 'я не спросил', answer: 'ich habe nicht gefragt', variants: habenArray, pronouns: pronounsArray },
        { id: 37, task: 'ты не спросил', answer: 'du hast nicht gefragt', variants: habenArray, pronouns: pronounsArray },
        { id: 38, task: 'он не спросил', answer: 'er hat nicht gefragt', variants: habenArray, pronouns: pronounsArray },
        { id: 39, task: 'она не спросила', answer: 'sie hat nicht gefragt', variants: habenArray, pronouns: pronounsArray },
        { id: 40, task: 'оно не спросило', answer: 'es hat nicht gefragt', variants: habenArray, pronouns: pronounsArray },
        { id: 41, task: 'мы не спросили', answer: 'wir haben nicht gefragt', variants: habenArray, pronouns: pronounsArray },
        { id: 42, task: 'вы не спросили', answer: 'ihr habt nicht gefragt', variants: habenArray, pronouns: pronounsArray },
        { id: 43, task: 'они не спросили', answer: 'sie haben nicht gefragt', variants: habenArray, pronouns: pronounsArray },
        { id: 44, task: 'Вы не спросили', answer: 'Sie haben nicht gefragt', variants: habenArray, pronouns: pronounsArray },

        { id: 45, task: 'я не любил', answer: 'ich habe nicht geliebt', variants: habenArray, pronouns: pronounsArray },
        { id: 46, task: 'ты не любил', answer: 'du hast nicht geliebt', variants: habenArray, pronouns: pronounsArray },
        { id: 47, task: 'он не любил', answer: 'er hat nicht geliebt', variants: habenArray, pronouns: pronounsArray },
        { id: 48, task: 'она не любила', answer: 'sie hat nicht geliebt', variants: habenArray, pronouns: pronounsArray },
        { id: 49, task: 'оно не любило', answer: 'es hat nicht geliebt', variants: habenArray, pronouns: pronounsArray },
        { id: 50, task: 'мы не любили', answer: 'wir haben nicht geliebt', variants: habenArray, pronouns: pronounsArray },
        { id: 51, task: 'вы не любили', answer: 'ihr habt nicht geliebt', variants: habenArray, pronouns: pronounsArray },
        { id: 52, task: 'они не любили', answer: 'sie haben nicht geliebt', variants: habenArray, pronouns: pronounsArray },
        { id: 53, task: 'Вы не любили', answer: 'Sie haben nicht geliebt', variants: habenArray, pronouns: pronounsArray },

        { id: 53, task: 'я не слышал', answer: 'ich habe nicht gehört', variants: habenArray, pronouns: pronounsArray },
        { id: 54, task: 'ты не слышал', answer: 'du hast nicht gehört', variants: habenArray, pronouns: pronounsArray },
        { id: 55, task: 'он не слышал', answer: 'er hat nicht gehört', variants: habenArray, pronouns: pronounsArray },
        { id: 56, task: 'она не слышала', answer: 'sie hat nicht gehört', variants: habenArray, pronouns: pronounsArray },
        { id: 57, task: 'оно не слышало', answer: 'es hat nicht gehört', variants: habenArray, pronouns: pronounsArray },
        { id: 58, task: 'мы не слышали', answer: 'wir haben nicht gehört', variants: habenArray, pronouns: pronounsArray },
        { id: 59, task: 'вы не слышали', answer: 'ihr habt nicht gehört', variants: habenArray, pronouns: pronounsArray },
        { id: 60, task: 'они не слышали', answer: 'sie haben nicht gehört', variants: habenArray, pronouns: pronounsArray },
        { id: 61, task: 'Вы не слышали', answer: 'Sie haben nicht gehört', variants: habenArray, pronouns: pronounsArray },

        { id: 62, task: 'я не ответил', answer: 'ich habe nicht geantwortet', variants: habenArray, pronouns: pronounsArray },
        { id: 63, task: 'ты не ответил', answer: 'du hast nicht geantwortet', variants: habenArray, pronouns: pronounsArray },
        { id: 64, task: 'он не ответил', answer: 'er hat nicht geantwortet', variants: habenArray, pronouns: pronounsArray },
        { id: 65, task: 'она не ответила', answer: 'sie hat nicht geantwortet', variants: habenArray, pronouns: pronounsArray },
        { id: 66, task: 'оно не ответило', answer: 'es hat nicht geantwortet', variants: habenArray, pronouns: pronounsArray },
        { id: 67, task: 'мы не ответили', answer: 'wir haben nicht geantwortet', variants: habenArray, pronouns: pronounsArray },
        { id: 68, task: 'вы не ответили', answer: 'ihr habt nicht geantwortet', variants: habenArray, pronouns: pronounsArray },
        { id: 69, task: 'они не ответили', answer: 'sie haben nicht geantwortet', variants: habenArray, pronouns: pronounsArray },
        { id: 70, task: 'Вы не ответили', answer: 'Sie haben nicht geantwortet', variants: habenArray, pronouns: pronounsArray },
    ],
    "pastQuestionStatements": [
        { id: 1, task: 'я сделал?', answer: 'habe ich gemacht?', variants: habenArray, pronouns: pronounsArray },
        { id: 2, task: 'ты сделал?', answer: 'hast du gemacht?', variants: habenArray, pronouns: pronounsArray },
        { id: 3, task: 'он сделал?', answer: 'hat er gemacht?', variants: habenArray, pronouns: pronounsArray },
        { id: 4, task: 'она сделала?', answer: 'hat sie gemacht?', variants: habenArray, pronouns: pronounsArray },
        { id: 5, task: 'оно сделало?', answer: 'hat es gemacht?', variants: habenArray, pronouns: pronounsArray },
        { id: 6, task: 'мы сделали?', answer: 'haben wir gemacht?', variants: habenArray, pronouns: pronounsArray },
        { id: 7, task: 'вы сделали?', answer: 'habt ihr gemacht?', variants: habenArray, pronouns: pronounsArray },
        { id: 8, task: 'они сделали?', answer: 'haben sie gemacht?', variants: habenArray, pronouns: pronounsArray },
        { id: 9, task: 'Вы сделали?', answer: 'haben Sie gemacht?', variants: habenArray, pronouns: pronounsArray },

        { id: 10, task: 'я танцевал', answer: 'habe ich getanzt?', variants: habenArray, pronouns: pronounsArray },
        { id: 11, task: 'ты танцевал', answer: 'hast du getanzt?', variants: habenArray, pronouns: pronounsArray },
        { id: 12, task: 'он танцевал', answer: 'hat er getanzt?', variants: habenArray, pronouns: pronounsArray },
        { id: 13, task: 'она танцевала', answer: 'hat sie getanzt?', variants: habenArray, pronouns: pronounsArray },
        { id: 14, task: 'оно танцевало', answer: 'hat es getanzt?', variants: habenArray, pronouns: pronounsArray },
        { id: 15, task: 'мы танцевали', answer: 'haben wir getanzt?', variants: habenArray, pronouns: pronounsArray },
        { id: 16, task: 'вы танцевали', answer: 'habt ihr getanzt?', variants: habenArray, pronouns: pronounsArray },
        { id: 17, task: 'они танцевали', answer: 'haben sie getanzt?', variants: habenArray, pronouns: pronounsArray },
        { id: 18, task: 'Вы танцевали', answer: 'haben Sie getanzt?', variants: habenArray, pronouns: pronounsArray },

        { id: 19, task: 'я играл', answer: 'habe ich gespielt?', variants: habenArray, pronouns: pronounsArray },
        { id: 20, task: 'ты играл', answer: 'hast du gespielt?', variants: habenArray, pronouns: pronounsArray },
        { id: 21, task: 'он играл', answer: 'hat er gespielt?', variants: habenArray, pronouns: pronounsArray },
        { id: 22, task: 'она играла', answer: 'hat sie gespielt?', variants: habenArray, pronouns: pronounsArray },
        { id: 23, task: 'оно играло', answer: 'hat es gespielt?', variants: habenArray, pronouns: pronounsArray },
        { id: 24, task: 'мы играли', answer: 'haben wir gespielt?', variants: habenArray, pronouns: pronounsArray },
        { id: 25, task: 'вы играли', answer: 'habt ihr gespielt?', variants: habenArray, pronouns: pronounsArray },
        { id: 26, task: 'они играли', answer: 'haben sie gespielt?', variants: habenArray, pronouns: pronounsArray },
        { id: 27, task: 'Вы играли', answer: 'haben Sie gespielt?', variants: habenArray, pronouns: pronounsArray },

        { id: 28, task: 'я сказал', answer: 'habe ich gesagt?', variants: habenArray, pronouns: pronounsArray },
        { id: 29, task: 'ты сказал', answer: 'hast du gesagt?', variants: habenArray, pronouns: pronounsArray },
        { id: 30, task: 'он сказал', answer: 'hat er gesagt?', variants: habenArray, pronouns: pronounsArray },
        { id: 31, task: 'она сказала', answer: 'hat sie gesagt?', variants: habenArray, pronouns: pronounsArray },
        { id: 32, task: 'оно сказало', answer: 'hat es gesagt?', variants: habenArray, pronouns: pronounsArray },
        { id: 33, task: 'мы сказали', answer: 'haben wir gesagt?', variants: habenArray, pronouns: pronounsArray },
        { id: 34, task: 'вы сказали', answer: 'habt ihr gesagt?', variants: habenArray, pronouns: pronounsArray },
        { id: 35, task: 'они сказали', answer: 'haben sie gesagt?', variants: habenArray, pronouns: pronounsArray },
        { id: 35, task: 'Вы сказали', answer: 'haben Sie gesagt?', variants: habenArray, pronouns: pronounsArray },

        { id: 36, task: 'я спросил', answer: 'habe ich gefragt?', variants: habenArray, pronouns: pronounsArray },
        { id: 37, task: 'ты спросил', answer: 'hast du gefragt?', variants: habenArray, pronouns: pronounsArray },
        { id: 38, task: 'он спросил', answer: 'hat er gefragt?', variants: habenArray, pronouns: pronounsArray },
        { id: 39, task: 'она спросила', answer: 'hat sie gefragt?', variants: habenArray, pronouns: pronounsArray },
        { id: 40, task: 'оно спросило', answer: 'hat es gefragt?', variants: habenArray, pronouns: pronounsArray },
        { id: 41, task: 'мы спросили', answer: 'haben wir gefragt?', variants: habenArray, pronouns: pronounsArray },
        { id: 42, task: 'вы спросили', answer: 'habt ihr gefragt?', variants: habenArray, pronouns: pronounsArray },
        { id: 43, task: 'они спросили', answer: 'haben sie gefragt?', variants: habenArray, pronouns: pronounsArray },
        { id: 44, task: 'Вы спросили', answer: 'haben Sie gefragt?', variants: habenArray, pronouns: pronounsArray },

        { id: 45, task: 'я любил', answer: 'habe ich geliebt?', variants: habenArray, pronouns: pronounsArray },
        { id: 46, task: 'ты любил', answer: 'hast du geliebt?', variants: habenArray, pronouns: pronounsArray },
        { id: 47, task: 'он любил', answer: 'hat er geliebt?', variants: habenArray, pronouns: pronounsArray },
        { id: 48, task: 'она любила', answer: 'hat sie geliebt?', variants: habenArray, pronouns: pronounsArray },
        { id: 49, task: 'оно любило', answer: 'hat es geliebt?', variants: habenArray, pronouns: pronounsArray },
        { id: 50, task: 'мы любили', answer: 'haben wir geliebt?', variants: habenArray, pronouns: pronounsArray },
        { id: 51, task: 'вы любили', answer: 'habt ihr geliebt?', variants: habenArray, pronouns: pronounsArray },
        { id: 52, task: 'они любили', answer: 'haben sie geliebt?', variants: habenArray, pronouns: pronounsArray },
        { id: 53, task: 'Вы любили', answer: 'haben Sie geliebt?', variants: habenArray, pronouns: pronounsArray },

        { id: 53, task: 'я слышал', answer: 'habe ich gehört?', variants: habenArray, pronouns: pronounsArray },
        { id: 54, task: 'ты слышал', answer: 'hast du gehört?', variants: habenArray, pronouns: pronounsArray },
        { id: 55, task: 'он слышал', answer: 'hat er gehört?', variants: habenArray, pronouns: pronounsArray },
        { id: 56, task: 'она слышала', answer: 'hat sie gehört?', variants: habenArray, pronouns: pronounsArray },
        { id: 57, task: 'оно слышало', answer: 'hat es gehört?', variants: habenArray, pronouns: pronounsArray },
        { id: 58, task: 'мы слышали', answer: 'haben wir gehört?', variants: habenArray, pronouns: pronounsArray },
        { id: 59, task: 'вы слышали', answer: 'habt ihr gehört?', variants: habenArray, pronouns: pronounsArray },
        { id: 60, task: 'они слышали', answer: 'haben sie gehört?', variants: habenArray, pronouns: pronounsArray },
        { id: 61, task: 'Вы слышали', answer: 'haben Sie gehört?', variants: habenArray, pronouns: pronounsArray },

        { id: 62, task: 'я ответил', answer: 'habe ich geantwortet?', variants: habenArray, pronouns: pronounsArray },
        { id: 63, task: 'ты ответил', answer: 'hast du geantwortet?', variants: habenArray, pronouns: pronounsArray },
        { id: 64, task: 'он ответил', answer: 'hat er geantwortet?', variants: habenArray, pronouns: pronounsArray },
        { id: 65, task: 'она ответила', answer: 'hat sie geantwortet?', variants: habenArray, pronouns: pronounsArray },
        { id: 66, task: 'оно ответило', answer: 'hat es geantwortet?', variants: habenArray, pronouns: pronounsArray },
        { id: 67, task: 'мы ответили', answer: 'haben wir geantwortet?', variants: habenArray, pronouns: pronounsArray },
        { id: 68, task: 'вы ответили', answer: 'habt ihr geantwortet?', variants: habenArray, pronouns: pronounsArray },
        { id: 69, task: 'они ответили', answer: 'haben sie geantwortet?', variants: habenArray, pronouns: pronounsArray },
        { id: 70, task: 'Вы ответили', answer: 'haben Sie geantwortet?', variants: habenArray, pronouns: pronounsArray },
    ],
    "questionWords": [
        { id: 1, task: 'Что?', answer: 'Was?', variants: questionWords },
        { id: 2, task: 'Кто?', answer: 'Wer?', variants: questionWords },
        { id: 3, task: 'Где?', answer: 'Wo?', variants: questionWords },
        { id: 4, task: 'Когда?', answer: 'Wann?', variants: questionWords },
        { id: 5, task: 'Почему?', answer: 'Warum?', variants: questionWords },
        { id: 6, task: 'Как?', answer: 'Wie?', variants: questionWords },
        { id: 7, task: 'Кого?', answer: 'Wen?', variants: questionWords },
    ],
}
